export enum State {
  SUBMITTING = 'SUBMITTING',
  SUBMITTED = 'SUBMITTED',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  // PARTIAL_SUCCESS = 'PARTIAL_SUCCESS',
  CANCELED = 'CANCELED',
  ERROR = 'ERROR',
  WAITING = 'WAITING'
}
