export enum Status {
  NOT_INITILIZED = 'NOT_INITILIZED',
  INITILIZED = 'INITIALIZED',
  CONNECTING = 'CONNECTING',
  RECONNECTING = 'RECONNECTING',
  WAITING_RECONNECT = 'WAITING_RECONNECT',
  LOGGED_IN = 'LOGGED_IN',
  LOG_UNKNOWN_FAIL = 'LOG_UNKNOWN_FAIL',
  AUTH_FAILED = 'AUTH_FAILED',
  OFFLINE = 'OFFLINE',
}
